In [1]:
2 ** 1000

10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376

In [2]:
import numpy as np

In [4]:
np.int64(2) ** 1000

0

In [5]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [6]:
len(arr)

3

In [7]:
arr[1]

2

In [8]:
type(arr[1])

numpy.int64

In [9]:
arr.dtype

dtype('int64')

In [10]:
arr32 = np.array([1,2,3], dtype=np.int32)
arr32

array([1, 2, 3], dtype=int32)

In [11]:
arr * arr

array([1, 4, 9])

In [12]:
v1 = np.random.rand(1000000)
v2 = np.random.rand(1000000)

In [13]:
%time v1 * v2

CPU times: user 3.38 ms, sys: 3.45 ms, total: 6.83 ms
Wall time: 4.99 ms


array([0.61922145, 0.11694783, 0.45657067, ..., 0.28769479, 0.06956236,
       0.35069864])

In [14]:
np.dot(arr, arr)


14

In [15]:
arr @ arr

14

In [16]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
v = np.arange(12)

In [18]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
v.reshape([4,3])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
mat = np.arange(12).reshape((4,3))
mat


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
mat.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [22]:
nums = [1,2,3,4,5]
nums[2:4]

[3, 4]

In [23]:
v = np.arange(1,6)
v[2:4]

array([3, 4])

In [24]:
arr = np.arange(12).reshape((3,4))

In [25]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
arr[0]

array([0, 1, 2, 3])

In [28]:
arr[:,1]

array([1, 5, 9])

In [29]:
arr[:,1].reshape((3,1))

array([[1],
       [5],
       [9]])

In [30]:
arr = np.arange(3)

In [31]:
arr

array([0, 1, 2])

In [32]:
arr[np.array([True, False, True])]

array([0, 2])

In [33]:
arr >= 1

array([False,  True,  True])

In [35]:
arr[arr>=1]

array([1, 2])

In [36]:
arr = np.arange(3)
arr + 4

array([4, 5, 6])

In [37]:
arr / 7

array([0.        , 0.14285714, 0.28571429])

In [38]:
mat = np.arange(9).reshape((3,3))
vec = np.arange(3)

In [39]:
mat + vec

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [41]:
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
vec

array([0, 1, 2])

In [43]:
v1 = np.arange(3)
v2 = np.arange(3).reshape((3,1))

In [44]:
v2

array([[0],
       [1],
       [2]])

In [45]:
v2.shape

(3, 1)

In [46]:
v1 + v2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [47]:
v1

array([0, 1, 2])

In [52]:
v = np.arange(12).reshape((4,3))
v

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [53]:
dir(v)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_e

In [55]:
v.any()

True

In [56]:
v.all()

False

In [57]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [58]:
v.prod()

0

In [59]:
v.sum(axis=1)

array([ 3, 12, 21, 30])

In [60]:
v.sum?

In [61]:
v.sum(axis=1, dtype=float)

array([ 3., 12., 21., 30.])

In [62]:
v1 = v.copy()

In [64]:
v1[0,0] = 1000
v1

array([[1000,    1,    2],
       [   3,    4,    5],
       [   6,    7,    8],
       [   9,   10,   11]])

In [65]:
data = v.dumps()
data

b'\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x04K\x03\x86q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00i8q\x0cK\x00K\x01\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89h\x03X`\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\t\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\x0b\x00\x00\x00\x00\x00\x00\x00q\x11h\x05\x86q\x12Rq\x13tq\x14b.'

In [66]:
v2 = np.loads(data)

In [67]:
v2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [68]:
np.sin(np.pi/2)

1.0

In [69]:
v = np.arange(-3,3)
np.sin(v)

array([-0.14112001, -0.90929743, -0.84147098,  0.        ,  0.84147098,
        0.90929743])

In [70]:
def noneg(n):
    if n < 0:
        return 0
    return n

In [71]:
noneg(7)

7

In [72]:
noneg(-3)

0

In [73]:
noneg(v)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [74]:
@np.vectorize
def noneg(n):
    if n < 0:
        return 0
    return n

In [75]:
def noneg(n):
    if n < 0:
        return 0
    return n
noneg = np.vectorize(noneg)

In [76]:
noneg(3)

array(3)

In [77]:
noneg(3).shape

()

In [78]:
noneg(v)

array([0, 0, 0, 0, 1, 2])

In [79]:
@np.vectorize
def noneg(n):
    if not np.isnan(n) and n < 0:
        return 0
    return n

In [80]:
nv = np.array([-1, np.nan, 1])

In [81]:
np.sin(nv)

array([-0.84147098,         nan,  0.84147098])

In [82]:
noneg(nv)

ValueError: cannot convert float NaN to integer

In [83]:
@np.vectorize
def noneg(n):
    if not np.isnan(n) and n < 0:
        return n.__class__(0)
    return n

In [84]:
noneg(nv)

array([ 0., nan,  1.])

In [86]:
np.int64(2) ** 4

16